//go:build !windows

package loom

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
)

// sys_install_unix.go — installation et désinstallation, partie commune à Linux
// et macOS. Les deux plateformes font exactement la même chose, à un détail
// près : la façon de déclarer les services (systemd d'un côté, launchd de
// l'autre). Ce détail vit dans sys_install_linux.go / sys_install_darwin.go,
// derrière deux fonctions : installServices et uninstallServices.
//
// Avant, chaque plateforme avait sa copie intégrale du parcours : deux fichiers
// identiques à 60 %, donc toute correction à faire deux fois. Comme le support
// macOS n'est pas testé sur une vraie machine, c'est précisément là qu'une
// divergence passait inaperçue.

func cmdInstall(args []string) error {
	if os.Geteuid() != 0 {
		return fmt.Errorf("loom install must run as root (sudo loom install)")
	}
	targetUser := os.Getenv("SUDO_USER")
	if targetUser == "" {
		targetUser = "root"
	}
	for _, a := range args {
		if strings.HasPrefix(a, "--user=") {
			targetUser = strings.TrimPrefix(a, "--user=")
		}
	}
	u, err := user.Lookup(targetUser)
	if err != nil {
		return fmt.Errorf("user '%s' not found: %w", targetUser, err)
	}
	loomHome := filepath.Join(u.HomeDir, ".local", "share", "loom")
	if v := os.Getenv("LOOM_HOME"); v != "" {
		loomHome = v
	}
	// Every step below (migration, folders, configuration) must target the
	// user's data, not root's: /etc/default/loom does not exist yet.
	_ = os.Setenv("LOOM_HOME", loomHome)
	adoptUserLoomHome()

	fmt.Printf("Installing for user %s\n", cyan(targetUser))
	fmt.Printf("  LOOM_HOME  = %s\n", loomHome)
	fmt.Printf("  services   = %s + %s\n", serviceName(), uiUnitName)

	// 0. Reprise d'une installation 0.7, si c'en est une. AVANT provisionDataDir :
	//    elle déplace des dossiers entiers, donc la destination ne doit pas
	//    encore exister. Code temporaire, voir migrate_07.go.
	if err := migrateFrom07(loomHome); err != nil {
		return fmt.Errorf("migrating 0.7 installation: %w", err)
	}

	// 1. Arborescence + configuration de départ.
	if err := provisionDataDir(); err != nil {
		return err
	}
	fmt.Printf("  %s directory structure ready\n", green("✓"))

	// 2. Lien vers /usr/local/bin/loom.
	if err := linkInstalledExe(); err != nil {
		return err
	}
	// 2b. Sur un système SELinux en mode enforcing (Fedora Atomic / Bazzite…),
	//     un binaire posé dans /usr/local/bin hérite du contexte user_home_t au
	//     lieu de bin_t : systemd refuse alors de l'exécuter (Permission denied,
	//     203/EXEC) tant qu'on n'a pas relancé restorecon à la main. On le fait
	//     ici, best-effort (issue #28).
	restoreconInstalledExe()

	// 3. /etc/default/loom, pour que les invocations root résolvent LOOM_HOME.
	if err := os.MkdirAll("/etc/default", 0o755); err != nil {
		return err
	}
	defaults := fmt.Sprintf("# Generated by loom install — data root\nLOOM_HOME=%s\n", loomHome)
	if err := os.WriteFile("/etc/default/loom", []byte(defaults), 0o644); err != nil {
		return err
	}
	fmt.Printf("  %s /etc/default/loom\n", green("✓"))

	// 4. Déclaration des services (systemd ou launchd selon la plateforme).
	if err := installServices(targetUser, loomHome); err != nil {
		return err
	}

	// 5. LOOM_HOME appartient à l'utilisateur cible : les deux services et les
	//    commandes qu'il tape doivent pouvoir écrire dans la base.
	chown(loomHome, u)

	fmt.Println()
	fmt.Printf("%s installation complete.\n", green("[ok]"))
	fmt.Printf("\nNext steps:\n")
	fmt.Printf("  1. point BIN to an existing llama-server:   %s\n", bold("sudo -u "+targetUser+" loom edit"))
	fmt.Printf("  2. choose the model (MODEL=…gguf) in the same file\n")
	fmt.Printf("  3. start the engine:   %s\n", bold("sudo loom start"))
	fmt.Printf("  4. check:              %s\n", bold("loom test"))
	fmt.Printf("  5. start the UI:       %s   (http://127.0.0.1:2510)\n", bold("sudo loom ui start"))
	return nil
}

// linkInstalledExe pose /usr/local/bin/loom sur le binaire courant.
//
// Garde-fou (issue #5) : si on tourne DÉJÀ depuis la cible — l'utilisateur a
// posé le binaire là puis lancé `sudo loom install` — il ne faut surtout pas
// Remove+Symlink sur soi-même : ça effacerait le vrai binaire et créerait un
// lien vers lui-même (« Too many levels of symbolic links »). On compare les
// chemins réels, résolus.
func linkInstalledExe() error {
	self, err := os.Executable()
	if err != nil {
		return err
	}
	if rp, e := filepath.EvalSymlinks(self); e == nil {
		self = rp
	}
	target := installedExePath()
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if tp, e := filepath.EvalSymlinks(target); e == nil && tp == self {
		fmt.Printf("  %s %s is already the installed binary (no link to create)\n", green("✓"), target)
		return nil
	}
	_ = os.Remove(target)
	if err := os.Symlink(self, target); err != nil {
		// Repli sur une copie si le lien échoue (volumes différents).
		data, rerr := os.ReadFile(self)
		if rerr != nil {
			return rerr
		}
		if werr := os.WriteFile(target, data, 0o755); werr != nil {
			return werr
		}
	}
	fmt.Printf("  %s %s -> %s\n", green("✓"), target, self)
	return nil
}

// restoreconInstalledExe recolle le bon contexte SELinux sur le binaire installé
// quand le système est en SELinux enforcing. Entièrement best-effort et
// silencieux hors SELinux : sur une machine sans SELinux, /sys/fs/selinux est
// absent et restorecon introuvable, on ne fait donc rien.
func restoreconInstalledExe() {
	// Signature d'un noyau SELinux monté : le pseudo-fs /sys/fs/selinux.
	if !isDir("/sys/fs/selinux") {
		return
	}
	if !hasTool("restorecon") {
		return
	}
	target := installedExePath()
	if rp, e := filepath.EvalSymlinks(target); e == nil {
		target = rp
	}
	// -F force le réétiquetage même si le contexte semble déjà correct.
	if err := hideCmd(exec.Command("restorecon", "-F", target)).Run(); err != nil {
		fmt.Printf("  %s restorecon failed (%v) — if systemd refuses to start (203/EXEC), run: restorecon -v %s\n",
			yellow("[warn]"), err, target)
		return
	}
	fmt.Printf("  %s SELinux context restored (restorecon) on %s\n", green("✓"), target)
}

func cmdUninstall(args []string) error {
	if os.Geteuid() != 0 {
		return fmt.Errorf("loom uninstall must run as root")
	}
	uninstallServices()
	for _, p := range []string{"/etc/default/loom", installedExePath()} {
		if err := os.Remove(p); err == nil {
			fmt.Printf("  %s %s\n", green("✓"), p)
		}
	}
	fmt.Println(dim("(user data preserved — delete $LOOM_HOME manually to purge)"))
	fmt.Println(green("[ok]") + " uninstalled")
	return nil
}

// chown donne récursivement path à l'utilisateur/groupe indiqué.
func chown(path string, u *user.User) {
	var uid, gid int
	fmt.Sscanf(u.Uid, "%d", &uid)
	fmt.Sscanf(u.Gid, "%d", &gid)
	_ = filepath.Walk(path, func(p string, info os.FileInfo, err error) error {
		if err == nil {
			_ = os.Chown(p, uid, gid)
		}
		return nil
	})
}
