// Code generated by tools/generate-codex-types.py from schema/messages.json; DO NOT EDIT.
package codexapp

import "encoding/json"

type InitializeParams struct {
	Capabilities json.RawMessage `json:"capabilities,omitempty"`
	ClientInfo   json.RawMessage `json:"clientInfo,omitempty"`
}
type InitializeResponse struct {
	CodexHome      json.RawMessage `json:"codexHome,omitempty"`
	PlatformFamily string          `json:"platformFamily,omitempty"`
	PlatformOs     string          `json:"platformOs,omitempty"`
	UserAgent      string          `json:"userAgent,omitempty"`
}
type ThreadStartParams struct {
	ApprovalPolicy        json.RawMessage `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     json.RawMessage `json:"approvalsReviewer,omitempty"`
	BaseInstructions      string          `json:"baseInstructions,omitempty"`
	Config                json.RawMessage `json:"config,omitempty"`
	Cwd                   string          `json:"cwd,omitempty"`
	DeveloperInstructions string          `json:"developerInstructions,omitempty"`
	Ephemeral             bool            `json:"ephemeral,omitempty"`
	Model                 string          `json:"model,omitempty"`
	ModelProvider         string          `json:"modelProvider,omitempty"`
	Personality           json.RawMessage `json:"personality,omitempty"`
	Sandbox               json.RawMessage `json:"sandbox,omitempty"`
	ServiceName           string          `json:"serviceName,omitempty"`
	ServiceTier           string          `json:"serviceTier,omitempty"`
	SessionStartSource    json.RawMessage `json:"sessionStartSource,omitempty"`
	ThreadSource          json.RawMessage `json:"threadSource,omitempty"`
}
type ThreadStartResponse struct {
	ApprovalPolicy     json.RawMessage `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer  json.RawMessage `json:"approvalsReviewer,omitempty"`
	Cwd                string          `json:"cwd,omitempty"`
	DisabledPluginIds  json.RawMessage `json:"disabledPluginIds,omitempty"`
	InstructionSources json.RawMessage `json:"instructionSources,omitempty"`
	Model              string          `json:"model,omitempty"`
	ModelProvider      string          `json:"modelProvider,omitempty"`
	ReasoningEffort    json.RawMessage `json:"reasoningEffort,omitempty"`
	Sandbox            json.RawMessage `json:"sandbox,omitempty"`
	ServiceTier        string          `json:"serviceTier,omitempty"`
	Thread             json.RawMessage `json:"thread,omitempty"`
}
type ThreadResumeParams struct {
	ApprovalPolicy        json.RawMessage `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     json.RawMessage `json:"approvalsReviewer,omitempty"`
	BaseInstructions      string          `json:"baseInstructions,omitempty"`
	Config                json.RawMessage `json:"config,omitempty"`
	Cwd                   string          `json:"cwd,omitempty"`
	DeveloperInstructions string          `json:"developerInstructions,omitempty"`
	ExcludeTurns          bool            `json:"excludeTurns,omitempty"`
	Model                 string          `json:"model,omitempty"`
	ModelProvider         string          `json:"modelProvider,omitempty"`
	Personality           json.RawMessage `json:"personality,omitempty"`
	Sandbox               json.RawMessage `json:"sandbox,omitempty"`
	ServiceTier           string          `json:"serviceTier,omitempty"`
	ThreadId              string          `json:"threadId,omitempty"`
}
type ThreadResumeResponse struct {
	ApprovalPolicy       json.RawMessage `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer    json.RawMessage `json:"approvalsReviewer,omitempty"`
	CollaborationMode    json.RawMessage `json:"collaborationMode,omitempty"`
	Cwd                  string          `json:"cwd,omitempty"`
	DisabledPluginIds    json.RawMessage `json:"disabledPluginIds,omitempty"`
	InstructionSources   json.RawMessage `json:"instructionSources,omitempty"`
	ItemsBackwardsCursor string          `json:"itemsBackwardsCursor,omitempty"`
	Model                string          `json:"model,omitempty"`
	ModelProvider        string          `json:"modelProvider,omitempty"`
	ReasoningEffort      json.RawMessage `json:"reasoningEffort,omitempty"`
	Sandbox              json.RawMessage `json:"sandbox,omitempty"`
	ServiceTier          string          `json:"serviceTier,omitempty"`
	Thread               json.RawMessage `json:"thread,omitempty"`
	TurnsBackwardsCursor string          `json:"turnsBackwardsCursor,omitempty"`
}
type ThreadListParams struct {
	Archived       bool            `json:"archived,omitempty"`
	Cursor         string          `json:"cursor,omitempty"`
	Cwd            json.RawMessage `json:"cwd,omitempty"`
	Limit          int64           `json:"limit,omitempty"`
	ModelProviders json.RawMessage `json:"modelProviders,omitempty"`
	Originators    json.RawMessage `json:"originators,omitempty"`
	SearchTerm     string          `json:"searchTerm,omitempty"`
	SectionId      string          `json:"sectionId,omitempty"`
	SortDirection  json.RawMessage `json:"sortDirection,omitempty"`
	SortKey        json.RawMessage `json:"sortKey,omitempty"`
	SourceKinds    json.RawMessage `json:"sourceKinds,omitempty"`
	UseStateDbOnly bool            `json:"useStateDbOnly,omitempty"`
}
type ThreadListResponse struct {
	BackwardsCursor string          `json:"backwardsCursor,omitempty"`
	Data            json.RawMessage `json:"data,omitempty"`
	NextCursor      string          `json:"nextCursor,omitempty"`
}
type ThreadReadParams struct {
	IncludeTurns bool   `json:"includeTurns,omitempty"`
	ThreadId     string `json:"threadId,omitempty"`
}
type ThreadReadResponse struct {
	Thread json.RawMessage `json:"thread,omitempty"`
}
type TurnStartParams struct {
	ApprovalPolicy      json.RawMessage `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer   json.RawMessage `json:"approvalsReviewer,omitempty"`
	ClientUserMessageId string          `json:"clientUserMessageId,omitempty"`
	Cwd                 string          `json:"cwd,omitempty"`
	DisabledPluginIds   json.RawMessage `json:"disabledPluginIds,omitempty"`
	Effort              json.RawMessage `json:"effort,omitempty"`
	Input               json.RawMessage `json:"input,omitempty"`
	Model               string          `json:"model,omitempty"`
	OutputSchema        json.RawMessage `json:"outputSchema,omitempty"`
	Personality         json.RawMessage `json:"personality,omitempty"`
	SandboxPolicy       json.RawMessage `json:"sandboxPolicy,omitempty"`
	ServiceTier         string          `json:"serviceTier,omitempty"`
	ServiceTierForTurn  string          `json:"serviceTierForTurn,omitempty"`
	Summary             json.RawMessage `json:"summary,omitempty"`
	ThreadId            string          `json:"threadId,omitempty"`
	ToolOutput          json.RawMessage `json:"toolOutput,omitempty"`
	TurnTrigger         string          `json:"turnTrigger,omitempty"`
}
type TurnStartResponse struct {
	Turn json.RawMessage `json:"turn,omitempty"`
}
type TurnInterruptParams struct {
	ThreadId string `json:"threadId,omitempty"`
	TurnId   string `json:"turnId,omitempty"`
}
type ModelListParams struct {
	Cursor        string `json:"cursor,omitempty"`
	IncludeHidden bool   `json:"includeHidden,omitempty"`
	Limit         int64  `json:"limit,omitempty"`
}
type ModelListResponse struct {
	Data       json.RawMessage `json:"data,omitempty"`
	NextCursor string          `json:"nextCursor,omitempty"`
}
type TurnStartedNotification struct {
	ThreadId string          `json:"threadId,omitempty"`
	Turn     json.RawMessage `json:"turn,omitempty"`
}
type TurnCompletedNotification struct {
	ThreadId string          `json:"threadId,omitempty"`
	Turn     json.RawMessage `json:"turn,omitempty"`
}
type ItemStartedNotification struct {
	Item        json.RawMessage `json:"item,omitempty"`
	StartedAtMs int64           `json:"startedAtMs,omitempty"`
	ThreadId    string          `json:"threadId,omitempty"`
	TurnId      string          `json:"turnId,omitempty"`
}
type ItemCompletedNotification struct {
	CompletedAtMs int64           `json:"completedAtMs,omitempty"`
	Item          json.RawMessage `json:"item,omitempty"`
	ThreadId      string          `json:"threadId,omitempty"`
	TurnId        string          `json:"turnId,omitempty"`
}
type AgentMessageDeltaNotification struct {
	Delta    string `json:"delta,omitempty"`
	ItemId   string `json:"itemId,omitempty"`
	ThreadId string `json:"threadId,omitempty"`
	TurnId   string `json:"turnId,omitempty"`
}
type ReasoningSummaryTextDeltaNotification struct {
	Delta        string `json:"delta,omitempty"`
	ItemId       string `json:"itemId,omitempty"`
	SummaryIndex int64  `json:"summaryIndex,omitempty"`
	ThreadId     string `json:"threadId,omitempty"`
	TurnId       string `json:"turnId,omitempty"`
}
type ReasoningTextDeltaNotification struct {
	ContentIndex int64  `json:"contentIndex,omitempty"`
	Delta        string `json:"delta,omitempty"`
	ItemId       string `json:"itemId,omitempty"`
	ThreadId     string `json:"threadId,omitempty"`
	TurnId       string `json:"turnId,omitempty"`
}
type CommandExecutionOutputDeltaNotification struct {
	Delta    string `json:"delta,omitempty"`
	ItemId   string `json:"itemId,omitempty"`
	ThreadId string `json:"threadId,omitempty"`
	TurnId   string `json:"turnId,omitempty"`
}
type FileChangeOutputDeltaNotification struct {
	Delta    string `json:"delta,omitempty"`
	ItemId   string `json:"itemId,omitempty"`
	ThreadId string `json:"threadId,omitempty"`
	TurnId   string `json:"turnId,omitempty"`
}
type TurnPlanUpdatedNotification struct {
	Explanation string          `json:"explanation,omitempty"`
	Plan        json.RawMessage `json:"plan,omitempty"`
	ThreadId    string          `json:"threadId,omitempty"`
	TurnId      string          `json:"turnId,omitempty"`
}
type TurnDiffUpdatedNotification struct {
	Diff     string `json:"diff,omitempty"`
	ThreadId string `json:"threadId,omitempty"`
	TurnId   string `json:"turnId,omitempty"`
}
type ThreadTokenUsageUpdatedNotification struct {
	ThreadId   string          `json:"threadId,omitempty"`
	TokenUsage json.RawMessage `json:"tokenUsage,omitempty"`
	TurnId     string          `json:"turnId,omitempty"`
}
type ErrorNotification struct {
	Error     json.RawMessage `json:"error,omitempty"`
	ThreadId  string          `json:"threadId,omitempty"`
	TurnId    string          `json:"turnId,omitempty"`
	WillRetry bool            `json:"willRetry,omitempty"`
}
type CommandExecutionRequestApprovalParams struct {
	ApprovalId                      string          `json:"approvalId,omitempty"`
	Command                         string          `json:"command,omitempty"`
	CommandActions                  json.RawMessage `json:"commandActions,omitempty"`
	Cwd                             json.RawMessage `json:"cwd,omitempty"`
	EnvironmentId                   string          `json:"environmentId,omitempty"`
	ItemId                          string          `json:"itemId,omitempty"`
	Kind                            json.RawMessage `json:"kind,omitempty"`
	NetworkApprovalContext          json.RawMessage `json:"networkApprovalContext,omitempty"`
	ProposedExecpolicyAmendment     json.RawMessage `json:"proposedExecpolicyAmendment,omitempty"`
	ProposedNetworkPolicyAmendments json.RawMessage `json:"proposedNetworkPolicyAmendments,omitempty"`
	Reason                          string          `json:"reason,omitempty"`
	StartedAtMs                     int64           `json:"startedAtMs,omitempty"`
	ThreadId                        string          `json:"threadId,omitempty"`
	TurnId                          string          `json:"turnId,omitempty"`
}
type CommandExecutionRequestApprovalResponse struct {
	Decision json.RawMessage `json:"decision,omitempty"`
}
type FileChangeRequestApprovalParams struct {
	GrantRoot   string `json:"grantRoot,omitempty"`
	ItemId      string `json:"itemId,omitempty"`
	Reason      string `json:"reason,omitempty"`
	StartedAtMs int64  `json:"startedAtMs,omitempty"`
	ThreadId    string `json:"threadId,omitempty"`
	TurnId      string `json:"turnId,omitempty"`
}
type FileChangeRequestApprovalResponse struct {
	Decision json.RawMessage `json:"decision,omitempty"`
}
type ToolRequestUserInputParams struct {
	AutoResolutionMs int64           `json:"autoResolutionMs,omitempty"`
	IsBlocking       bool            `json:"isBlocking,omitempty"`
	ItemId           string          `json:"itemId,omitempty"`
	Questions        json.RawMessage `json:"questions,omitempty"`
	ThreadId         string          `json:"threadId,omitempty"`
	TurnId           string          `json:"turnId,omitempty"`
}
type ToolRequestUserInputResponse struct {
	Answers json.RawMessage `json:"answers,omitempty"`
}
type McpServerElicitationRequestParams struct {
	Meta            json.RawMessage `json:"_meta,omitempty"`
	ElicitationId   string          `json:"elicitationId,omitempty"`
	Message         string          `json:"message,omitempty"`
	Mode            string          `json:"mode,omitempty"`
	RequestedSchema json.RawMessage `json:"requestedSchema,omitempty"`
	ServerName      string          `json:"serverName,omitempty"`
	ThreadId        string          `json:"threadId,omitempty"`
	TurnId          string          `json:"turnId,omitempty"`
	Url             string          `json:"url,omitempty"`
}
type McpServerElicitationRequestResponse struct {
	Meta    json.RawMessage `json:"_meta,omitempty"`
	Action  string          `json:"action,omitempty"`
	Content json.RawMessage `json:"content,omitempty"`
}
type PermissionsRequestApprovalParams struct {
	Cwd           string          `json:"cwd,omitempty"`
	EnvironmentId string          `json:"environmentId,omitempty"`
	ItemId        string          `json:"itemId,omitempty"`
	Permissions   json.RawMessage `json:"permissions,omitempty"`
	Reason        string          `json:"reason,omitempty"`
	StartedAtMs   int64           `json:"startedAtMs,omitempty"`
	ThreadId      string          `json:"threadId,omitempty"`
	TurnId        string          `json:"turnId,omitempty"`
}
type PermissionsRequestApprovalResponse struct {
	Permissions      json.RawMessage `json:"permissions,omitempty"`
	Scope            json.RawMessage `json:"scope,omitempty"`
	StrictAutoReview bool            `json:"strictAutoReview,omitempty"`
}
type ServerRequestResolvedNotification struct {
	RequestId json.RawMessage `json:"requestId,omitempty"`
	ThreadId  string          `json:"threadId,omitempty"`
}
