#!/usr/bin/env python3
"""Generate only Loom's message projections from a CLI-generated schema snapshot.
Complex/union fields remain RawMessage: unknown variants must survive translation.
"""
import json, pathlib, subprocess, sys
root = pathlib.Path(__file__).resolve().parents[1] / 'internal/loom/runtime/codexapp'
source = pathlib.Path(sys.argv[1]) if len(sys.argv)>1 else root/'schema'
names = '''InitializeParams InitializeResponse ThreadStartParams ThreadStartResponse ThreadResumeParams ThreadResumeResponse ThreadListParams ThreadListResponse ThreadReadParams ThreadReadResponse TurnStartParams TurnStartResponse TurnInterruptParams ModelListParams ModelListResponse TurnStartedNotification TurnCompletedNotification ItemStartedNotification ItemCompletedNotification AgentMessageDeltaNotification ReasoningSummaryTextDeltaNotification ReasoningTextDeltaNotification CommandExecutionOutputDeltaNotification FileChangeOutputDeltaNotification TurnPlanUpdatedNotification TurnDiffUpdatedNotification ThreadTokenUsageUpdatedNotification ErrorNotification CommandExecutionRequestApprovalParams CommandExecutionRequestApprovalResponse FileChangeRequestApprovalParams FileChangeRequestApprovalResponse ToolRequestUserInputParams ToolRequestUserInputResponse McpServerElicitationRequestParams McpServerElicitationRequestResponse PermissionsRequestApprovalParams PermissionsRequestApprovalResponse ServerRequestResolvedNotification'''.split()
if source != root/'schema':
    defs = {}
    for name in names:
        schema=json.loads(next(source.rglob(name+'.json')).read_text())
        defs.update(schema.pop('definitions',{}));defs[name]=schema
    (root/'schema/messages.json').write_text(json.dumps({'$schema':'http://json-schema.org/draft-07/schema#','definitions':defs},indent=2)+'\n')
    (root/'schema/VERSION').write_text('codex-cli 0.159.2\n')
schemas=json.loads((root/'schema/messages.json').read_text())['definitions']
def go_type(s):
    if not isinstance(s,dict): return 'json.RawMessage'
    if '$ref' in s:
        return go_type(schemas[s['$ref'].split('/')[-1]])
    t=s.get('type');t=next((x for x in t if x!='null'),None) if isinstance(t,list) else t
    return {'string':'string','integer':'int64','number':'float64','boolean':'bool'}.get(t,'json.RawMessage')
def field(k):
    return k[0].upper()+k[1:] if k[0].isalpha() else 'Meta'
lines=['// Code generated by tools/generate-codex-types.py from schema/messages.json; DO NOT EDIT.','package codexapp','import "encoding/json"']
for name in names:
    s=schemas[name];props=dict(s.get('properties',{}))
    # Union request parameters share an envelope; retain all arm fields.
    for arm in s.get('oneOf',[]):props.update(arm.get('properties',{}))
    lines.append('type '+name+' struct {')
    for k,v in sorted(props.items()):
        lines.append(f'{field(k)} {go_type(v)} `json:"{k},omitempty"`')
    lines.append('}')
(root/'types_generated.go').write_text('\n'.join(lines)+'\n')
subprocess.run(['gofmt','-w',str(root/'types_generated.go')],check=True)
